### ISSUE TITLE
I can't find anywhere a comprehensive manual to configure de DeepDeck

### ISSUE THREAD

**Issue by reguer** [DeepSea-Developments/DeepDeck.Ahuyama.fw#12]
Hello! 

I bought the deep deck because I read you could use it with Notion and the screenshots of the "dashboard" seemed really intuitive. Now that I have mine, I've been able to use only whats place by default. All the "tutorials" or wikis lead me to Github repositories (which Im totally unfamiliar with) but if there's a clear path to use the "app" please share it with me.

Please help! :)

**Comment by electronick-co** [comment]
Hi @reguer 

We are finishing the release for having the dashboard live. It has taken us a little bit longer than we expected but we are working on it, and with the team, we plan to have a version ready this week.

Please enter our discord channel where we will be given all the updates. We are also in the process of updating the webpage with all the info, so there will be more info on how to do all the updates in an easy way!

Here is a link with all the links https://linktr.ee/deepdeck

Thanks for your patience, and I will make sure you will be able to take advantage of DeepDeck. Also mention that is a live project, so there will be a lot of updates coming soon!
