### ISSUE TITLE
Settings page, improve readability.

### ISSUE THREAD

**Issue by Slugsie** [DeepSea-Developments/DeepDeck.Ahuyama.fw#16]
Currently the settings page has a dark grey background, with grey text. Which is very hard to read. Specifically the text in the lower part of each 'key' has a colour of '#69635b' on a background of '#50431f'. Please make the font colour closer to white. I find that changing the colour of the upper text to #eee and the lower text to #ccc looks good and is readable.

Poor readability:
![Bad](https://github.com/DeepSea-Developments/DeepDeck.Ahuyama.fw/assets/3976650/0fb1dae4-c6af-4975-8f47-6e2e48103661)

Better readability:
![Good](https://github.com/DeepSea-Developments/DeepDeck.Ahuyama.fw/assets/3976650/3ad7e44d-0457-401a-9e7f-27a00d8baa15)

**Comment by Slugsie** [comment]
BTW, Firmware v0.5.5

**Comment by electronick-co** [comment]
solved in develop branch.
Will be released on version 0.5.6

**Comment by electronick-co** [comment]
Solved in v 0.5.6
