### ISSUE TITLE
Macro names inconsistent

### ISSUE THREAD

**Issue by Slugsie** [DeepSea-Developments/DeepDeck.Ahuyama.fw#17]
There is an inconsistency in the naming of the Macros. On the Keymap/Macro page they're named macro_1/macro_1 through macro_36/macro36.

Screen shot (I've been experimenting with the macros so the first few are renamed).
![Macro_1](https://github.com/DeepSea-Developments/DeepDeck.Ahuyama.fw/assets/3976650/3312d82e-a85a-4695-98d3-dbff36f0e31f)

However on the Macro page they're named macro_1/M0 through macro_36/M35
![Macro_2](https://github.com/DeepSea-Developments/DeepDeck.Ahuyama.fw/assets/3976650/5aa892ff-5755-4416-b660-eea9391e3821)

This is inconsistent, and confusing. Both screens should use the same naming convention. I suggest the one used by the Keymap page as macro_36 being the name for Macro M35 doesn't make any sense.

Firmware 0.5.5

**Comment by electronick-co** [comment]
Solved in v 0.5.6
