### ISSUE TITLE
Macros with names longer than 3 characters break.

### ISSUE THREAD

**Issue by Slugsie** [DeepSea-Developments/DeepDeck.Ahuyama.fw#18]
If I create a Macro, and give it a name of more than 3 characters then it appears to save OK. However If you then close the macro page and go back you'll find the Macro name is blank. It allows you to enter a name of up to 7 characters.

Created new Macro named 'ABCD'. Saved, all looks good.
![Macro_A](https://github.com/DeepSea-Developments/DeepDeck.Ahuyama.fw/assets/3976650/022c1e73-d893-4343-b814-984eb755a058)

Now go to the Keymap page, then back to the Macro Page:
![Macro_B](https://github.com/DeepSea-Developments/DeepDeck.Ahuyama.fw/assets/3976650/1af23aca-3c16-455f-a86e-029cbf749c23)

Changing the name to 3 characters and it works:
![Macro_C](https://github.com/DeepSea-Developments/DeepDeck.Ahuyama.fw/assets/3976650/5e35c8ba-04bf-4a70-8e79-ff46e870eebe)

Given keys can have labels up to 6 characters, the macro names should probably be limited to 6 characters, but they should definitely work beyond 3.

Firmware v0.5.5

**Comment by Slugsie** [comment]
Also, on a side note about macro names. I just noticed that several of the default keys use Macros. I.e. the Copy and Paste action on the Media layer use M33 and M34 respectively. I think the Macros should be named appropriately by default to reflect their default actions otherwise it's not obvious what they all do, or that editing them might affect the built in layers.

**Comment by electronick-co** [comment]
Ready on develop branch.
Will be available from version 0.5.6

**Comment by electronick-co** [comment]
Solver in v0.5.6
