### ISSUE TITLE
link to documentation

### ISSUE THREAD

**Issue by jdimpson** [DeepSea-Developments/DeepDeck.Ahuyama.fw#3]
I can't find the usage documentation anywhere on [deepdeck.co](deepdeck.co). I see it in the /doc folder of this repo, but its not apparent on your published web site. I can look at the docs on github, but the internal hyperlinks don't work right due to github/markdown weirdness.

**Comment by electronick-co** [comment]
Hi @jdimpson 
The documentation is now updated on the webpage and you can also join our discord server to share ideas or ask questions!
