### ISSUE TITLE
Http failure response for http://null/api/layers

### ISSUE THREAD

**Issue by estiens** [DeepSea-Developments/DeepDeck.Ahuyama.fw#40]
I often have to reload the webserver 4/5 times to get this error to go away, without nothing can be done

**Comment by rickyphewitt** [comment]
I received this a few times when I initially setup my DeepDeck. Turning off an adblocked I had in my browser seemed to help. But Trying it this morning with adblocker on/off I do not see this problem. 

Have you tried different browsers just to rule that out as well as disabling any plugins?

**Comment by electronick-co** [comment]
Go to the settings webpage and test the connection.
We are going to release a new version solving some bugs on how it works and then put this as a priority, to avoid users to have to manually confirm it. Sorry for the inconvenience

![image](https://github.com/DeepSea-Developments/DeepDeck.Ahuyama.fw/assets/5274871/8c89263d-d94a-474f-8b18-eab2f6cc1543)
