### ISSUE TITLE
Clear up the Known Issues Page

### ISSUE THREAD

**Issue by trwbox** [DeepSea-Developments/DeepDeck.Ahuyama.fw#6]
Some of these known issues appear to be fixed, specifically the ones relating to USB hardware implementation. https://github.com/DeepSea-Developments/DeepDeck.Ahuyama.fw/blob/main/docs/known-issues.md

Specifically I have tested a USB-C to USB-C cable on an M1 MacBook Pro, and it appears to power and detect the DeepDeck in all 4 possible options. I also have not been able to trigger the issue where USB-A to USB-C orientation breaks programming, no matter matter the orientation, and on multiple USB systems.

**Comment by electronick-co** [comment]
You are right, those were a past version. I updated the documentation. Thanks!
